### ISSUE TITLE
Bug in rendering single-child paths to side nav

### ISSUE THREAD

**Issue by theRemix** [grommet/grommet-swagger#11]
path : `/about/versions` should appear on the side nav

https://developer.hpe.com/api/onesphere/endpoint?&path=/about/versions

**Comment by karatechops** [comment]
Thanks for turning this around so quickly. This looks to fix the issue but I would like just the base route to display in the nav - if we look at the following example only `zones` should be rendered in the nav. Additionally, `about/versions` in the nav should only render as `about`
![screen shot 2018-07-27 at 11 28 38 am](https://user-images.githubusercontent.com/5983843/43330122-4b621cac-9190-11e8-9e21-0ff9359f3bea.png)

**Comment by theRemix** [comment]
This commit fixes the issue so that *zones* appears just once


https://github.com/theRemix/grommet-swagger/commit/710d9fe025e42a9cea3dbc01263b176768a5a848
