### ISSUE TITLE
Add Disable Markdown Feature

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet-swagger#16]
As some Swagger references are automatically generated, most do not account for the Markdown rendering. We end up with unintended emphasis tags when referencing things like my_object_id. As this behavior can not be disabled in markdown-to-jsx (#15) my suggestion is we add a feature to disable Markdown 

@ericsoderberghp any other suggestions? Maybe within the swagger spec itself the user can define a boolean in a `useMarkdown` key. grommet-swagger can always default to true if the value is not present, this way we do not need to change any 1S documentation.

**Comment by ericsoderberghp** [comment]
Would it make any sense to escape characters like '_' and '*' before sending to Markdown?

**Comment by karatechops** [comment]
Closed in favor of PR #18
