### ISSUE TITLE
Swagger description is incorrect for GET /rest/zone/{id}/task-status

### ISSUE THREAD

**Issue by RenukaPrasad** [grommet/grommet-swagger#23]
The swagger for GET /rest/zone/{id}/task-status shows a meaningless description for the responses.
**Responses 200**

**Gets the task status for zone**
esxLcmTask
 "infrastructure-system-task"
{{}}

**While in Postman I can see this:**
{{}}
{
    "operationState": "",
    "uuid": "d0bc878b-8a6e-11e8-a210-0683149e9e44",
    "uri": "/rest/tasks/d0bc878b-8a6e-11e8-a210-0683149e9e44",
    "type": "infrastructure-system-task",
    "created": "2018-07-18T09:41:58.784514002Z",
    "modified": "2018-07-18T09:54:12.940726341Z",
    "name": "EnableAndDisable Resources",
    "parentId": "",
    "childTasks": null,
    "percentComplete": 100,
    "error":
{         "message": "",         "details": "",         "recommendedActions": null,         "nestedErrors": null,         "errorSource": "",         "errorCode": "",         "data": null,         "canForce": false     },
    "description": "",
    "progressUpdates": [],
    "associatedResourceType": "infrastructure-system-list",
    "associatedResourceInstanceName": "",
    "associatedResourceInstanceId": "",
    "associatedResourceInstanceUri": "/rest/infrastructure-systems",
    "taskType": "",
    "state": "Completed",
    "status": "OK",
    "isPartialSuccess": false,
    "terminalState": false,
    "taskFailed": false,
    "inUse": false,
    "weight": 1,
    "eTag": "",
    "tag": ""
}
{{}}
{{}}

**Comment by karatechops** [comment]
Fixed in 0.2.1 refactor. this route now returns a correct example of 
```json
{
  "associatedResourceInstanceId": "",
  "associatedResourceInstanceName": "",
  "associatedResourceInstanceUri": "",
  "associatedResourceType": "zone",
  "childTasks": [
    "00ccc1fc-b7f1-11e7-bb3f-0242ac110003"
  ],
  "created": "2017-10-23T12:52:18.356685887Z",
  "description": "Update inventory element",
  "eTag": "",
  "error": {
    "canForce": false,
    "data": null,
    "details": "",
    "errorCode": "",
    "errorSource": "",
    "message": "",
    "nestedErrors": null,
    "recommendedActions": null
  },
  "inUse": false,
  "isPartialSuccess": false,
  "modified": "2017-10-23T12:53:18.742575801Z",
  "name": "HCOE_ISM_INVENTORY_UPDATE",
  "operationState": "",
  "parentId": "",
  "percentComplete": 100,
  "progressUpdates": [
    {
      "statusUpdate": "Total capacity requested is 10 ",
      "timeStamp": "2017-12-07T03:53:02.127808703Z"
    },
    {
      "statusUpdate": "Total capacity successfully added is 5",
      "timeStamp": "2017-12-07T03:53:02.132827168Z"
    }
  ],
  "state": "Completed",
  "status": "OK",
  "tag": "",
  "taskFailed": false,
  "taskType": "",
  "terminalState": false,
  "type": "infrastructure-system-task",
  "uri": "/rest/infrastructure-system-tasks/009fc27b-b7f1-11e7-bb3f-0242ac110003",
  "uuid": "009fc27b-b7f1-11e7-bb3f-0242ac110003",
  "weight": 1
}
```
